#pragma once

#define ONBOARD_LED_PIN GPIO_PIN_5
#define ONBOARD_LED_GPIO_PORT GPIOA

#define USART_TX_Pin GPIO_PIN_2
#define USART_TX_GPIO_Port GPIOA
#define USART_RX_Pin GPIO_PIN_3
#define USART_RX_GPIO_Port GPIOA
